/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "notebook.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

struct contact *
create_1(contact *argp, CLIENT *clnt)
{
	static struct contact clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, create,
		(xdrproc_t) xdr_contact, (caddr_t) argp,
		(xdrproc_t) xdr_contact, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct contact *
read_1(contact *argp, CLIENT *clnt)
{
	static struct contact clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, read,
		(xdrproc_t) xdr_contact, (caddr_t) argp,
		(xdrproc_t) xdr_contact, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct contact *
update_1(contact *argp, CLIENT *clnt)
{
	static struct contact clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, update,
		(xdrproc_t) xdr_contact, (caddr_t) argp,
		(xdrproc_t) xdr_contact, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

struct contact *
delete_1(contact *argp, CLIENT *clnt)
{
	static struct contact clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, delete,
		(xdrproc_t) xdr_contact, (caddr_t) argp,
		(xdrproc_t) xdr_contact, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
