/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _NOTEBOOK_H_RPCGEN
#define _NOTEBOOK_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct contact {
	char name[500];
	char number[500];
	char address[500];
};
typedef struct contact contact;

#define NOTEBOOK_PROG 12345678
#define NOTEBOOK_VERSION 1

#if defined(__STDC__) || defined(__cplusplus)
#define create 1
extern  struct contact * create_1(contact *, CLIENT *);
extern  struct contact * create_1_svc(contact *, struct svc_req *);
#define read 2
extern  struct contact * read_1(contact *, CLIENT *);
extern  struct contact * read_1_svc(contact *, struct svc_req *);
#define update 3
extern  struct contact * update_1(contact *, CLIENT *);
extern  struct contact * update_1_svc(contact *, struct svc_req *);
#define delete 4
extern  struct contact * delete_1(contact *, CLIENT *);
extern  struct contact * delete_1_svc(contact *, struct svc_req *);
extern int notebook_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define create 1
extern  struct contact * create_1();
extern  struct contact * create_1_svc();
#define read 2
extern  struct contact * read_1();
extern  struct contact * read_1_svc();
#define update 3
extern  struct contact * update_1();
extern  struct contact * update_1_svc();
#define delete 4
extern  struct contact * delete_1();
extern  struct contact * delete_1_svc();
extern int notebook_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_contact (XDR *, contact*);

#else /* K&R C */
extern bool_t xdr_contact ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_NOTEBOOK_H_RPCGEN */
